behaviors:
  TrackDriverBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120 
      buffer_size: 409600
      learning_rate: 1.0e-3
      beta: 1.0e-3
      epsilon: 0.2 
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10.0e6
    time_horizon: 2048
    summary_freq: 25000
    keep_checkpoints: 5
    checkpoint_interval: 500000
