default_settings: null
behaviors:
  botCollision_behaviour_Nate:
    trainer_type: ppo
    hyperparameters:
      batch_size: 40000
      buffer_size: 80000
      learning_rate: 3.0e-06
      beta: 0.0005
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 175
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.991
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
      gail:
        gamma: 0.99
        strength: 0.7
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
        learning_rate: 7.0e-05
        encoding_size: null
        use_actions: false
        use_vail: false
        demo_path: Demos
    init_path: results\CollisionBrain_session_6\botCollision_behaviour_Nate
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 100000000000000000000
    time_horizon: 64
    summary_freq: 10000
    threaded: false
    self_play: null
    behavioral_cloning:
      demo_path: Demos
      steps: 0
      strength: 0.5
      samples_per_update: 0
      num_epoch: null
      batch_size: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: CollisionBrain_session_7
  initialize_from: CollisionBrain_session_6
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
