behaviors:
  BotCollision_Hyperparams:
    trainer_type: ppo
    hyperparameters:
      batch_size: 20000
      buffer_size: 40000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 175
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.991
        strength: 1.0
    max_steps: 2e6
    time_horizon: 64
    summary_freq: 10000