behaviors:
  botCollision_behaviour_Nate:
    trainer_type: ppo
    hyperparameters:
      batch_size: 40000
      buffer_size: 80000
      learning_rate: 3.0e-5
      beta: 5.0e-4
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 175
      num_layers: 2
    reward_signals:
      # reinforsment learning
      extrinsic:
        strength: 1
        gamma: 0.991
      # Generative Adversarial Imitation Learning (gail) - builds a NN that is evaluated against the performance of the demo 
      #  --does not require a lot of demos to work well--
      gail:
        strength: 0.4
        demo_path: Demos
        learning_rate: 7.0e-5
        use_vail: false 
    # immitation learning - Trains the agent to mimic the demos
    #  --requires a lot of demos to work well--
    behavioral_cloning:
        strength: 0.3
        demo_path: Demos
    max_steps: 1e20
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 500000